### ISSUE TITLE
Suport of Text and/or FontIcons

### ISSUE THREAD

**Issue by nicHoch** [bradmartin/nativescript-floatingactionbutton#20]
Hi

thanks for the good plugin.

Would it be possible to add an support for a Text within the FAB and even better the support of Icon Fonts.

Nicky

**Comment by bradmartin** [comment]
Hi @nicHoch - that's a good idea. However, I don't think that will work for the native Android control. It might, but would require a lot more time to "hack" something than I have right now. If you want to try and get it working I'll accept a PR.

**Comment by bradmartin** [comment]
After a little more research this is not something supported by the component and would involve a hack to make it work. As such we won't support it with this plugin. If you want text your best option is to create and image with your text and use it instead.

**Comment by giovannicandido** [comment]
Any toughs on https://github.com/NathanWalker/nativescript-ng2-fonticon and https://github.com/NathanWalker/nativescript-fonticon ?

Could a integration work?

**Comment by bradmartin** [comment]
https://developer.android.com/reference/android/support/design/widget/FloatingActionButton.html since it descends from `ImageView`, the native android component doesn't support font or text out of the box. I'm sure there is some way with some serious changes made to extend the functionality but I don't have the time to implement this and I can't find a quick sample from any Android forum/discussions on implementing this. Here is a great site to get all the density icons you need for native apps: https://material.io/icons/

Hope that helps 😄

**Comment by giovannicandido** [comment]
@bradmartin Thanks, your response clarify the question.

I solve my case using http://fa2png.io/ to convert from fontawesome to png.
