### ISSUE TITLE
'hideOnSwipeOfView' does not work for RadListView

### ISSUE THREAD

**Issue by felix-idf** [bradmartin/nativescript-floatingactionbutton#38]
Hi,

the FAB plugin works perfekt on a default ListView, but the _hideOnSwipeOfView_ functionality seems not to work for a RadListView from Telerik UI for NativeScript ... or maybe I use it the wrong way?!
I thought putting an ID to the ListView and assigning this ID to the _hideOnSwipeOfView_ property should be enough, it seems to be the right way for a usual ListView at least.

```
<lv:RadListView
        id="myListView"
     ... >
    <lv:RadListView.itemTemplate>
        ...
    </lv:RadListView.itemTemplate>
</lv:RadListView>
<FAB:fab
     hideOnSwipeOfView="myListView"
     ... 
/>
```

Best regards

**Comment by bradmartin** [comment]
It's an issue with RadListView. Could you open a bug about gestures not
working on that component. Sorry. I've been thru it and unfortunately
nothing I can do cause the code here checks out and works fine :(

On Tue, Nov 8, 2016, 4:34 AM seppel1992 <notifications@github.com> wrote:

Hi,

the FAB plugin works perfekt on a default ListView, but the
*hideOnSwipeOfView* functionality seems not to work for a RadListView from
Telerik UI for NativeScript ... or maybe I use it the wrong way?!
I thought putting an ID to the ListView and assigning this ID to the
*hideOnSwipeOfView* property should be enough, it seems to be the right way
for a usual ListView at least.

<lv:RadListView
        id="myListView"
     ... >
    <lv:RadListView.itemTemplate>
        ...
    </lv:RadListView.itemTemplate>
</lv:RadListView>
<FAB:fab
     hideOnSwipeOfView="myListView"
     ...
/>

Best regards

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bradmartin/nativescript-floatingactionbutton/issues/38>,
or mute the thread

**Comment by sitefinitysteve** [comment]
I'll put in an official ticket with them

**Comment by seppel1992** [comment]
Ok, I guessed it already :)
Thanks for your help!

**Comment by AceTheFace** [comment]
For me this is still an issue....do you have a link to the official ticket, please?

**Comment by dyazincahya** [comment]
It looks like i have the same problem in nativescript 3.2.1 hmm -_-

**Comment by mikolino** [comment]
RadListView doesn't support the pan event. I'm not sure why fab uses pan over scroll, perhaps because pan has a handy delta for changes.

For anyone looking for an immediate solution I wrote code to work with RadListView:

https://gist.github.com/mikolino/c66e48f43e132ababc6ec576d71b0e8b

It's basically a copy paste of FAB's hiding code + added variables, and the code goes with your other event handlers for the radlistview.
