### ISSUE TITLE
HELP: How to keep fab on display when keyboard is active on screen.

### ISSUE THREAD

**Issue by dbilovd** [bradmartin/nativescript-floatingactionbutton#88]
I have a FAB displaying at the bottom of the screen. The problem is when a user starts typing and the keyboard takes up half the screen, it also covers the FAB. Is there anyway I can handle this and still have the FAB always displayed?

**Comment by bradmartin** [comment]
The way this works on native android is by using CoordinatorLayout. Since that is not something I've seen exposed with NS core or via a plugin, your current options are to detect the keyboard opening/closing and animate the FAB or change its position in your layout so that it's visible above the keyboard. I've not done this myself, but should be possible to work something out, might take a little trial and error.
